near/react-on-chain

packages/iframe/src/SandboxedIframe.tsx
This PR explicitly assigns names to inlined function definitions in order to preserve names after minification of imported code.
=> fix: provide explicit names for inlined function definitions

packages/iframe/src/SandboxedIframe.tsx
This PR adds aliases for external functions whose definitions are inlined into the iframe container. Since external functions are minified before deployment, they will have one-character names in their definitions and within references to each other. Other Component container code refers to them by their original names, so these external functions must be addressable by either the minified or original name.
In development mode, the functions are not minified and therefore do not require aliases. Therefore the assignment of aliases is dynamic based on whether the original name is being used.
=> fix: aliases for minified external functions

apps/web/hooks/useComponentMetrics.ts, apps/web/hooks/useWebEngine.ts, apps/web/pages/index.tsx, packages/application/src/handlers.ts, packages/application/src/index.ts, packages/application/src/monitor.tsx, packages/application/src/types.ts, packages/compiler/src/compiler.ts, packages/compiler/src/component.ts, packages/container/src/events.ts, packages/container/src/hooks.ts, packages/container/src/serialize.ts, packages/container/src/types.ts, packages/iframe/src/SandboxedIframe.tsx, pnpm-lock.yaml
This PR adds a new `Widget` prop, `id`, intended to explicitly identify the Component:
```jsx
<Widget src="a.near/widget/ChildComponent" id="A" />
<Widget src="a.near/widget/ChildComponent" id="B />
```
This fixes #13.
Included in this PR are fixes for unrelated issues around state and metrics that were bugging me so I've included their fixes here as well. I tried to fix the regressions around state management but ultimately settled on temporarily disabling re-renders based on state changes. Sandboxed loading is now mostly unaffected but trusted loading is not handling state correctly as it is not distinguishing between instances of the same Component. I'll have follow up PRs to address these issues but want to truncate this one here.
=> feat: explicit Component IDs

apps/web/hooks/useWebEngine.ts, packages/application/src/monitor.tsx, packages/application/src/widget-container.ts, packages/compiler/src/component.ts, packages/compiler/src/parser.ts, packages/container/src/serialize.ts, packages/container/src/types.ts
This PR updates the Component state logic to allow trusted Component instances to parse their own IDs dynamically. This is done with the use of a `parentMeta` property on the `__bweMeta` object, analogous to prototype chains.
=> feat: state enhancements and fixes

apps/web/pages/index.tsx, packages/compiler/src/component.ts, packages/container/src/events.ts, packages/container/src/serialize.ts, packages/iframe/src/SandboxedIframe.tsx
This PR fixes rendering for sandboxed Components when `State.update()` is called. Historically the problem with this has been that Components may call `State.update()` at render time, triggering cascading renders until the call stack between `renderComponent()` and `State.update()` overflows.
I'm not convinced that supporting these `State.update()` invocations are a practical use case, and would prefer they ultimately be replaced with `useEffect` when available. My interim solution is to ignore re-render requests triggered by `State.update` when the Component has either:
- not finished rendering the initial render
- not re-rendered since the last update-triggered render
In my testing this pattern is still supported, but it's likely that this breaks assumptions on how this is expected to …
=> feat: sandboxed state

apps/web/hooks/useWebEngine.ts, packages/compiler/src/parser.ts
Took this opportunity to update the path validation to use the full regex for NEAR accounts since I am deploying some test components to `bwe-demos.near` which was failing due to the hyphen
=> use regex from nomicon for account ID

apps/web/hooks/useFlags.ts, apps/web/hooks/useWebEngine.ts, apps/web/package.json, apps/web/pages/flags.tsx, apps/web/workers/compiler.ts, packages/compiler/src/compiler.ts, pnpm-lock.yaml
closes #28 
- adds `flags.tsx` page for managing application flags which are persisted to localstorage, this is reached by manually navigating to `/flags`. This is backed by the `useFlags` hook for reading+writing flags
- adds `styled-components` and `react-hook-form` to the outer window application because `flags.tsx` was pulled from the near/near-discovery repo. We do not have a strong need for them at the moment, and the page could easily be refactored to exclude them, but those are good libs to have on hand anyways for other outer application work
- modifies compiler web worker to handle multiple `action` types when processing message. Previous action is now referred to as `execute` and a new action was added called `init` for passing in params i.e. bos-loader URL
- if a bos-loader …
=> local component development support

apps/web/components/ComponentTree.tsx, apps/web/hooks/useWebEngine.ts, packages/application/src/container.ts, packages/compiler/src/compiler.ts, packages/compiler/src/component.ts, packages/compiler/src/parser.ts, packages/container/src/callbacks.ts, packages/container/src/events.ts, packages/container/src/serialize.ts, packages/container/src/types.ts, packages/iframe/src/SandboxedIframe.tsx
This PR rounds out the trusted loading implementation by inlining trusted Components within the parent container and only renders its descendants as trusted if they have explicitly opted into it.
I've also updated the workaround for dealing with `State.update()` calls on render to ignore `State`-triggered re-renders with the same value. This will fail for values that always change (e.g. `State.update({ t: Date.now() })`) but should suffice until hooks are implemented. Upside is that state updates now re-render automatically.
Closes #73
=> feat: explicit trust

apps/web/components/ComponentTree.tsx, components.md, packages/application/package.json, packages/application/src/handlers.ts, packages/application/src/types.ts, packages/common/.eslintrc.js, packages/common/package.json, packages/common/src/index.ts, packages/common/src/types.ts, packages/common/tsconfig.json, packages/compiler/package.json, packages/compiler/src/compiler.ts, packages/compiler/src/parser.ts, packages/container/package.json, packages/container/src/messaging.ts, packages/container/src/serialize.ts, packages/container/src/types.ts, packages/iframe/package.json, packages/iframe/src/SandboxedIframe.tsx, pnpm-lock.yaml
This PR replaces the `isTrusted` flag with an object under `trust` to accommodate more complex loading strategies in the future. Fixes #72 
Before:
```jsx
<Widget isTrusted ... />
```
After:
```jsx
<Widget trust={{ mode: "trusted" }} ... />
```
The options in the current implementation are implemented here as values for `mode`: `sandboxed` or `trusted`. In the updated implementation (#73), Components without a value specified are assumed to be `sandboxed`.
As part of this PR I've also included a ~trust-author~ `trusted-author` trust mode, which treats all Components as trusted if they have the same author as the Component loaded with this trust mode. However explicitly indicating `sandboxed` mode overrides this blanket trust for individual Components and their descendants:
```jsx
{/* Root …
```
=> feat: replace `isTrusted`

apps/web/components/Inspector.tsx, apps/web/hooks/useWebEngine.ts, apps/web/next.config.js, apps/web/package.json, apps/web/pages/[[...root]].tsx, apps/web/stores/component-sources.ts, packages/compiler/src/compiler.ts, pnpm-lock.yaml
closes #56 
Creates an always-present, collapsible code inspector panel for viewing original component source. In the future, we may want to drive this by a flag of some sort in order to ensure it is not affecting performance, but for now we gain more by having it always running so users discover it naturally instead of needing to go looking for it.
Also adds Zustand for basic global state management. If we end up expanding its usage, we can learn from the [Pagoda Console implementation](https://github.com/near/pagoda-console/tree/develop/frontend/stores)
=> add code inspector panel

turbo.json
several of our packages build to `lib` and they were not being cached by turborepo, causing them to be missing when Vercel has a cache hit on those packages
should resolve our intermittent build failures
=> add lib to turbo cache

packages/container/src/container.ts, packages/container/src/types.ts, packages/iframe/src/SandboxedIframe.tsx
Fixes #112 
I was mistaken about the root cause for this initially, turns out all that's needed is to inline the stringified JSON when passing as an argument. I had broken it in the refactor to get JS out of the iframe container template string, but this solution removes a lot of unnecessary jank and clears the way for removing the encoding functions altogether 🎉
=> fix: inline stringified JSON props directly

apps/web/.env, apps/web/hooks/useWebEngine.ts, components.md, packages/compiler/src/parser.ts, packages/compiler/src/source.ts, packages/container/src/render.ts
~Note: this breaks bos-loader until I make an update there to offer a flag to determine whether to use VM or BWE syntax~(release 0.8.0 is up)
closes #131
=> Drop `/widget/` from component paths

packages/application/src/container.ts
This PR expands the set of values included on DOM event objects and calls `preventDefault` until Components have a way to specify that behavior.
=> feat: add fields and prevent default

apps/web/components/ComponentTree.tsx, apps/web/hooks/useWebEngine.ts, packages/compiler/src/compiler.ts, packages/compiler/src/component.ts, packages/compiler/src/import.ts, packages/compiler/src/index.ts, packages/compiler/src/source.ts, packages/compiler/src/types.ts, packages/container/src/render.ts, packages/iframe/src/SandboxedIframe.tsx
This PR adds support for `import` statements in BOS Components. The functionality is pretty rigid but provides an accessible way to begin testing `import` compatibility.
The functionality being added is meant to make transitions from a React application simpler while granting the flexibility to provide direct URL imports for overriding default behavior and testing. Currently `esm.sh` is the default provider, as it supports dynamic bundling and specification of dependency versions - allowing hooks within the imported package to work within BWE.
Supported syntax:
```js
// imports the current version from esm.sh with bundled Preact
import X from "x";
// imports the specified version from esm.sh with bundled Preact
import X from "x@1.2.3";
// imports the module at the URL directly
import X …
```
=> feat: imports

packages/compiler/src/parser.ts, packages/container/src/container.ts, packages/container/src/render.ts, packages/container/src/serialize.ts, packages/container/src/types.ts, packages/iframe/src/SandboxedIframe.tsx
This PR adds the `<Component />` Component, which will eventually replace `<Widget />`. I've implemented them side-by-side here with a warning to begin migrating to `<Component />`.
When we're ready we can phase it out completely by following up with #153
=> feat: allow use of <Component />

packages/compiler/src/compiler.ts
Reverts near/bos-web-engine#149
these fixes were necessary only for an outdated and bugged version of bos-loader
=> Revert "fix: fix local component fetching"

packages/compiler/src/compiler.ts, packages/compiler/src/component.ts, packages/compiler/src/export.ts, packages/iframe/src/SandboxedIframe.tsx
This PR adds support for the `export` keyword, which indicates to BWE that the exported reference is the Component to be rendered for this path.
The following variations are supported:
```js
export default X;
export default function X ...
export function X ...
export const X = ...
```
=> feat: add support for `export` keyword

packages/compiler/src/compiler.ts, packages/compiler/src/component.ts, packages/compiler/src/export.ts, packages/compiler/src/parser.ts
This PR deprecates support for the JSX body Components in favor of JS modules which export a Component. The supported `export` statements are:
```js
export default XYZ; // any valid identifier is OK here
export function BWEComponent... // must be named BWEComponent
export const BWEComponent... // must be named BWEComponent
```
I'll hold off merging until we can coordinate updates for this breaking change.
=> feat: require default or named export

packages/application/src/components/SandboxedIframe.tsx, packages/compiler/src/parser.ts, packages/container/src/container.ts, packages/container/src/render.ts, packages/container/src/serialize.ts, packages/container/src/types.ts
This PR removes `<Widget />` as the Component for importing BOS Components. Once merged, only `<Component />` references will be valid.
=> feat: deprecate Widget

apps/web/components/ComponentMonitor.tsx, packages/application/src/container.ts, packages/application/src/handlers.ts, packages/common/src/types/messaging.ts, packages/common/src/types/render.ts, packages/common/src/types/serialization.ts, packages/container/src/callbacks.ts, packages/container/src/container.ts, packages/container/src/events.ts, packages/container/src/messaging.ts, packages/container/src/serialize.ts, packages/container/src/types.ts
This PR permits nesting functions within objects/arrays on `props`. Fixes #121 and a slew of edge cases related to callbacks and cross-container argument passing.
=> feat: support nested props

apps/demos/globals.d.ts, apps/demos/src/StateAndTrust/TrustTree.tsx, packages/sandbox/src/constants.ts
This PR adds typings in `apps/demos` and `apps/sandbox` for `useCallback`, along with updating demos using `useCallback` to specify dependencies.
=> feat: useCallback typedef

apps/demos/src/LandingPage.tsx, apps/web/pages/[[...root]].tsx, packages/application/src/handlers.ts, packages/application/src/hooks/useWebEngine.ts, packages/application/src/types.ts
This PR restores the functionality for rendering CSS borders to delineate the DOM trees rendered by individual containers. The landing page Component has been updated, and the URL parameter name has been changed to reflect the end behavior. The configuration could also be moved to a flag if that makes more sense than a query parameter.
Marking this as a draft for now since there is an issue where trusted Components will erroneously display a label when a subset of the DOM is rerendered. This is based on the now-faulty assumption that there is a 1:1 between containers and DOM roots, which was broken when the Preact integration was fixed to re-render only changed subsets of the DOM tree.
Addresses part of #175 (monitor should probably just mimic the `Code` tab)
=> feat: restore option to show container boundaries

packages/compiler/src/parser.ts, packages/container/src/render.ts
This PR fixes an inconsistency in how `props` are treated on trusted Components. Going forward, Component-level props (e.g. `src`, `id`) will be accessible to trusted children as metadata, i.e. `props.__bweMeta.src`.
Fixes #211
=> fix: trusted IDs

packages/application/src/components/ComponentTree.tsx, packages/application/src/hooks/useComponents.ts, packages/common/src/types/render.ts, packages/compiler/src/compiler.ts, packages/compiler/src/source.ts, packages/compiler/src/types.ts, packages/container/src/serialize.ts, packages/sandbox/src/components/Preview.tsx
This PR parses a new `css` key on responses from Components sources (sandbox, `bos-loader`, or on-chain), aggregating stylesheets at the container level. Component-level CSS is wrapped by selectors to encapsulate styles, restricting them to be applied to instances of that component within that container.
There is not a convenient way of uploading CSS at the moment so I have created #221 as a way to test locally.
=> feat: CSS compilation

apps/demos/globals.d.ts, apps/demos/src/LandingPage.tsx, apps/demos/src/Posts/Account.tsx, apps/demos/src/Posts/Feed.tsx, apps/demos/src/Posts/Marked.tsx, apps/demos/src/StateAndTrust/TrustTree.tsx, architecture.md, packages/application/src/components/SandboxedIframe.tsx, packages/application/src/hooks/useComponents.ts, packages/compiler/src/import.ts, packages/compiler/src/transpile.ts, packages/sandbox/src/constants.ts
This PR implements imports of `react`, `preact`, and `react-dom` (all using Preact) and fixes bugs around namespace imports. With these dependencies now importable, I went ahead and cleaned up the global variables in the container context.
After merging this, references to React hooks must be imported:
```js
import { useCallback } from 'react';
```
alternatively:
```js
import { useCallback } from 'preact/hooks';
```
Fixes #225
=> feat: import enhancements

packages/application/src/components/SandboxedIframe.tsx, packages/compiler/src/parser.ts
This PR fixes `props` references for root Components without a `props` argument. Also fixes bad references in the container update logic.
Both were bugs leftover from the purging of global references #227
=> fix: invalid props references

packages/application/src/hooks/useCompiler.ts, packages/application/src/hooks/useComponents.ts, packages/application/src/hooks/useWebEngine.ts, packages/application/src/hooks/useWebEngineSandbox.ts, packages/application/src/types.ts, packages/application/src/workers/compiler.ts, packages/common/src/types/compilation.ts, packages/common/src/types/index.ts, packages/compiler/src/compiler.ts, packages/compiler/src/index.ts, packages/compiler/src/source.ts, packages/compiler/src/types.ts, packages/sandbox/package.json, packages/sandbox/src/components/Preview.tsx, pnpm-lock.yaml
This PR introduces the `useCompiler` hook, refactoring it out of `useComponents` for direct use within the `useWebEngine*` hooks. This fixes some mis-mapped behavior from the refactor of these methods that needed to be fixed as a prerequisite for #219
In addition, the sandbox-specific call to the compiler worker has been removed. Its behavior has been rolled into the existing `init` call, which is now made whenever any of the compiler parameters (Preact version, sandbox IDE Components, etc.) are updated. Exposing the compiler interface to the `useWebEngine*` hooks while parameterizing their divergent behavior is a net benefit here, and does some of the ground work necessary for a future web worker responsible for managing BWE Component source fetching/caching.
=> feat: useCompiler hook

packages/compiler/src/parser.ts
This PR fixes a bug with props injection at build time. When `props` is the first key specified, the parsed match expects a leading `{`. This character is not expected when the first key is not `props`, so the workaround is to move the substring index to the previous character - `{` in this case. If `props` is the first key, this now-excluded character is whitespace and the index change is a no-op.
Fixes #245
=> fix: Component props order

apps/demos/src/StateAndTrust/Root.tsx, apps/demos/src/StateAndTrust/SetParent.tsx, apps/demos/src/StateAndTrust/Shape/Circle.tsx, apps/demos/src/StateAndTrust/Shape/Square.tsx, apps/demos/src/StateAndTrust/Shape/Triangle.tsx, apps/demos/src/StateAndTrust/ShapeSet.tsx, apps/demos/src/StateAndTrust/TrustTree.tsx, packages/compiler/src/compiler.ts, packages/compiler/src/component.ts, packages/compiler/src/import.ts, packages/compiler/src/parser.ts, packages/compiler/src/types.ts
This PR updates the `import` syntax to support importing BWE Components statically. Relative and full imports are supported.
Components may now be referenced as:
```jsx
import Form from 'ex.near/Form'; // for an absolute reference to a Component
import Button from './Button'; // for a Component in the same folder
...
<Form id="form" props={...} />
<Button id="button" props={...} />
```
instead of
```jsx
<Component src="ex.near/Form" id="form" props={...} />
<Component src="me.near/Button" id="button" props={...} />
```
Note that the latter form (`<Component src="..." />`) is still supported after making this change.
Destructured imports are not supported with this change. Currently BWE Modules must have either a default export or an export named `BWEComponent`, which the new behavior …
=> feat: Component imports

packages/compiler/src/export.ts
This PR fixes the `export` functionality to accommodate more valid expressions, including:
- `function X() { ... } ... export default X;`
- `const X = () => (...); ... export { X as BWEComponent }`
=> fix: export references

packages/container/src/render.ts
Nested fragments with invalid markup aren't supported. So, for example, this won't work:
```jsx
<>
<>
text
</>
<>
```
But this *does* work in React. Part of the issue is that when fragments don't contain valid markup, React will just happily insert it into the DOM anyway. So this is "valid" React code 😬. 
Basically we were [crashing here](https://github.com/near/bos-web-engine/blob/835bd57d9fd4a9f88b63a4183f95d5c019555295/packages/application/src/react.ts#L80-L89) because `children` did not contain any elements. 
Valid `children`:
Invalid `children`:
Notice the null type here.
**For Valid Children**: If a fragment's children are all valid nodes (meaning, they have a type), they're returned directly. This keeps our DOM clean and avoids adding unnecessary wrappers.
**For Invalid Children**: …
=> Support Nested Fragments

packages/application/src/hooks/useComponents.ts, packages/application/src/hooks/useCss.ts, packages/application/src/hooks/useWebEngine.ts, packages/application/src/hooks/useWebEngineSandbox.ts, packages/application/src/types.ts, packages/compiler/src/compiler.ts, packages/compiler/src/component.ts, packages/compiler/src/css.ts, packages/compiler/src/import.ts, packages/compiler/src/text.ts, packages/compiler/src/types.ts
This PR adds support for basic CSS module syntax, i.e. top-level class selectors without nesting:
```css
.wrapper {
padding: 1em;
}
```
Components may specify CSS class as strings:
```jsx
<div className="wrapper">
``` 
or via import:
```jsx
/*
currently the path isn't validated, anything matching
`./*.module.css` will be interpreted as a CSS module
*/
import styles from './Wrapper.module.css';
...
<div className="wrapper">
``` 
CSS module class names are transformed with UUID substrings. They are generated per Component so there is no guarantee of uniqueness, though possibility of collision is vanishingly small.
Fixes #252
=> feat: CSS modules

packages/sandbox/src/components/MonacoDiff.tsx, packages/sandbox/src/components/MonacoEditor.tsx, packages/sandbox/src/constants.ts, packages/sandbox/src/hooks/useSandboxStore.ts
Updating our Sandbox with our new import/export syntax. I've added a short term type fix by providing a helper type `BWEComponent` globally in the sandbox:
```tsx
type Props = {
message: string;
foo: number;
};
function Message({ message }: Props) {
return (
<div className="wrapper">
<h2>BOS Says:</h2>
<p>{message}</p>
</div>
);
}
export default Message as BWEComponent<Props>;
```
Now we have proper type safety for component `props` thanks to @andy-haynes work supporting relative imports! We'll rework this a bit once this is completed: https://github.com/near/bos-web-engine/issues/261
=> Sandbox: Updated Example Imports

packages/container/src/render.ts, packages/container/src/serialize.ts
This PR adds a missing check for Preact nodes when recursively serializing props. Since Preact nodes reference themselves, serialization triggered a stack overflow.
Fixes #265
=> fix: check for Preact nodes when serializing props

packages/sandbox/src/constants.ts, packages/ui/src/components/Button.module.css
Updated the sandbox examples to use proper CSS Module import syntax since it's now supported: https://github.com/near/bos-web-engine/pull/264#issuecomment-1936428262
Anyone who's familiar with CSS Modules will immediately recognize what's going on: 
```tsx
import s from './styles.module.css';
type Props = {
message?: string;
};
function MyComponent({ message = "Hello!" }: Props) {
return (
<div className={s.wrapper}>
<p>{message}</p>
</div>
);
}
export default MyComponent as BWEComponent<Props>;
```
=> Sandbox: proper CSS Module import syntax

apps/demos/src/LandingPage.tsx, apps/demos/src/NPM/Tracker.tsx, apps/demos/src/NPM/Tracker/ComponentEntry.tsx, apps/web/src/components/Inspector.tsx
- add entry to LandingPage to get to compatability tracker
- add tracker for grouping npm demos by status
- add query param to allow code inspector to start in expanded state
closes #215
=> tracking page for npm compatability demos

packages/container/src/serialize.ts
This PR strips invalid `props` keys when serializing rendered Components to be sent to the outer application. These are probably coming from JSX transpilation in the compiler worker.
Fixes #249
=> fix: strip invalid React prop keys

packages/sandbox/src/hooks/useFileWithMonaco.ts
Closes: https://github.com/near/bos-web-engine/issues/277
As of now, Monaco doesn't have support for native CSS nesting syntax (it shows a bunch of errors when you do). A quick, short term fix is using the built in support for `SCSS` syntax.
=> Short term fix for CSS nesting syntax (use SCSS syntax)

packages/compiler/src/import.ts
This PR updates the import parsing logic to split out Babel-generated helper function declarations: https://babeljs.io/docs/babel-plugin-transform-runtime
Fixes #291
=> split out generated function declarations

apps/web/.env, packages/sandbox/src/components/FileOpener.tsx
Closes: https://github.com/near/bos-web-engine/issues/286
Closes: https://github.com/near/bos-web-engine/issues/287
Improved styles and types for our `LandingPage` and `SocialFeedPage` components. Since we don't have `bos-cli` set up to handle CSS modules just yet, @mpeterdev had me go ahead and fork and publish these new components on `webengine.near` (using the Sandbox UI).
The `SocialFeedPage` demonstrates using a breakpoint to change spacing on smaller screens.
I went ahead and updated `NEXT_PUBLIC_DEFAULT_ROOT_COMPONENT` in Vercel as well.
=> Improved Demos

apps/sandbox/package.json, apps/sandbox/src/constants.ts, apps/web/package.json, apps/web/src/constants.ts, packages/sandbox/src/hooks/useSandboxStore.ts, pnpm-lock.yaml
Closes: https://github.com/near/bos-web-engine/issues/284
Since My Near Wallet requires a full page redirect, I'm now persisting `mode` in the sandbox store to improve UX when redirected back to the sandbox after publishing. This way you can still see the UI that confirms your changes were published.
=> My Near Wallet

packages/compiler/src/types.ts, packages/social-db-api/src/constants.ts
Closes: https://github.com/near/bos-web-engine/issues/179
Closes: https://github.com/near/bos-web-engine/issues/178
One thing to keep in mind is that `deploy-components-main.yml` will still be deploying our `demos` folder for `bwe-demos.near` to the `widget` namespace due to the usage of `bos` CLI.
This means that all `bwe-demos.near` components will throw an error:
- https://bos-web-engine-git-feat-alpha-com-02bf22-near-developer-console.vercel.app/bwe-demos.near/StateAndTrust.Root
- Clicking any of the links on this page will be broken too: https://bos-web-engine-git-feat-alpha-com-02bf22-near-developer-console.vercel.app/webengine.near/NPM.Tracker
@mpeterdev we might need to fork and publish all `bwe-demos.near` components through the sandbox UI (moving everything over to …
=> Component Alpha Namespace

apps/demos/src/WalletSelector/SignAndSendTransaction.tsx
This PR updates the demo `signAndSendTransaction` Component to use NEAR instead of yNEAR.
Fixes #321
=> feat: use Near denomination for demo

apps/web/src/pages/[[...root]].tsx, packages/application/src/components/ComponentTree.tsx, packages/application/src/handlers.ts, packages/sandbox/src/components/FileExplorer.module.css, packages/sandbox/src/components/Preview.tsx, packages/wallet-selector-control/src/components/WalletSelectorControl.module.css, packages/wallet-selector-plugin/src/index.ts
Closes: https://github.com/near/bos-web-engine/issues/311
Exposes `getAccounts` through our existing wallet selector plugin. This allows components to know what `accountId` and `publicKey` the user is signed in with (or if they aren't signed in at all, which would be an empty array).
I did need to add an adjustment to `<ComponentTree />` to re-render the entire tree when the current account changes. I left a detailed note in the source code. I believe we were going to need to make a change like this at some point regardless. Forcefully re-rendering the entire component tree when the wallet context changes (user signs in or out) should help avoid all kinds of issues for component authors down the road.
Without this change to `<ComponentTree />`, if you signed in or signed out without …
=> getAccounts()

packages/compiler/src/compiler.ts
This PR removes the old CSS concatenation logic preventing trusted Component CSS from rendering as expected.
Fixes #307
=> fix: trusted CSS

packages/application/src/react.ts, packages/application/src/types.ts, packages/compiler/src/compiler.ts, packages/compiler/src/transpile.ts
This PR adds logic around excluding executable code via bundling or rendering:
- `<script>` tags are now stripped out of input Component source
- `</script>` literals are removed from code to prevent early termination of the `<script>` within the container iframe `srcDoc`
- `<script>` tags can no longer be created from rendered DOM (i.e. no injection via `window.postMessage({ type: "component.render" })`)
- `props` with executable JS as values are stripped out.
Fixes #226
=> fix: script injection

packages/application/src/react.ts
This PR removes the check for a leading `#` as a `props` value as it is overly-restrictive
=> fix: remove filter for '#'

apps/demos/globals.d.ts, packages/application/src/components/SandboxedIframe.tsx, packages/application/src/container.ts, packages/common/src/types/render.ts, packages/common/src/types/serialization.ts, packages/compiler/src/transpile.ts, packages/container/src/container.ts, packages/container/src/index.ts, packages/container/src/render.ts, packages/container/src/serialize.ts, packages/container/src/types.ts, packages/sandbox/src/constants.ts
This PR updates the props interface to consolidate the web engine config props into a single object, allowing Component props to be inlined at the top level instead of under a `props` key (fixes #261). Additionally, the top-level `id` prop has been replaced by `key` (fixes #335).
All changes are backward compatible, though the sandbox IDE typing will reflect the new usage - legacy usage will be squiggly'd.
See example:
```jsx
import { useState } from 'react';
import Message from './Message';
import s from './styles.module.css';
function HelloWorld() {
const [count, setCount] = useState(0);
return (
<div className={s.wrapper}>
<h1>Welcome!</h1>
{/*
This legacy usage will be supported at runtime but will now throw TS errors
Warnings will be displayed in the console
*/}
<Message …
```
=> feat: new props interface

packages/compiler/src/transpile.ts
This PR handles the case in which an empty `bwe` object is checked for a `trust` key
=> fix: empty `bwe` props

apps/web/.env, packages/compiler/src/transpile.ts, packages/container/src/render.ts, packages/container/src/serialize.ts
This PR deprecates support for legacy style props for Components, i.e.
- specifying `id` instead of `key` as a top-level prop
- putting Component props under `props` - these should be specified as top-level prop keys
- specifying `trust` or `src` as top-level props - these should go under the `bwe` prop
As a breaking change, this should only be merged once the changes have been announced and devs have had time to migrate. Both styles are supported in the interim.
=> feat: deprecate legacy props

packages/application/src/hooks/useWebEngineSandbox.ts
This PR removes the superfluous call to the compiler worker's `init` method in the `useWebEngineSandbox` hook. Since this method is now called as part of the `useCompiler` hook with overlapping dependencies, the call in `useWebEngineSandbox` is at best a no-op and at worst creates a race condition.
Potential fix for #382
=> feat: remove superfluous compiler init

packages/compiler/src/transpile.ts
This PR fixes support for spread props (`<C key="x" {...props} />`) that was broken after converting to the new `props` interface. Fixes #389 
Note that the `bwe` props value continues to support only literals.
=> fix: props spread

apps/demos/src/AlphaDashboardPage.tsx, apps/demos/src/SocialFeedPage.tsx
We are using `Button` components with a children prop but the children prop only works for trusted components at the moment
This is a worthwhile optimization anyways, so no need to revert once the children prop is supported on sandboxed components
=> fix buttons in demos by making them trusted

packages/common/src/types/render.ts, packages/compiler/src/transpile.ts, packages/container/src/render.ts
This PR fixes component IDs for trusted Components. By combining the Component path (known at build time) and the Component `key` along with the path/`key` combinations for its ancestors traced up to the root Component. Currently this only gets set at the root container, which this change fixes by constructing the Component ID recursively at render time.
Current behavior: https://bos-web-engine.vercel.app/bwe-demos.near/StateAndTrust.Root?showContainerBoundaries=false
Fixed behavior: https://bos-web-engine-git-fix-component-7c1578-near-developer-console.vercel.app/bwe-demos.near/StateAndTrust.Root?showContainerBoundaries=false
E.g. for this Component structure
```js
<Parent key="p" bwe={{ trust: { mode: 'trusted-author' } }}>
<Child key="c" />
</Parent>
```
The ID for `Child` is currently …
=> fix: construct component IDs on demand

apps/web/src/components/WebEngineVariants.tsx, packages/application/src/hooks/useCompiler.ts, packages/application/src/hooks/useComponents.ts, packages/application/src/hooks/useWebEngine.ts, packages/application/src/hooks/useWebEngineSandbox.ts, packages/application/src/types.ts, packages/compiler/src/compiler.ts, packages/compiler/src/import.ts, packages/compiler/src/types.ts, packages/sandbox/src/components/Preview.tsx, packages/sandbox/src/constants.ts
This PR updates the way Preact dependencies are imported and specified for third-party packages. In particular:
- Preact version is no longer configurable outside the compiler
- Preact dependencies are specified as `stable/` builds to ensure the same instance is used within the imported package
- Preact dependencies are marked as `external` to ensure only one instance of Preact is used
- `preact/compat` import paths have been updated to include the ~build hash (`X-YS9yZWFjdDpwcmVhY3QvY29tcGF0`) that appears to always be imported by `esm.sh` bundles when `react` is swapped out for `preact/compat`~ subpaths required when marking `preact` as an external dependency
This fixes #323 and unblocks progress on importing other libraries (tested with `@chakra-ui` so far), though the latter still …
=> feat: Preact versioning

packages/compiler/src/source.ts
This PR updates the accessor for the `css` field on SocialDB responses to not assume the existence of a key.
=> fix: CSS not guaranteed on Component responses

packages/sandbox/src/components/SidebarActions.module.css, packages/sandbox/src/components/SidebarActions.tsx
=> add confirmation dialog to sandbox reset button

apps/web/src/components/Messaging.tsx, packages/application/src/components/SandboxedIframe.tsx, packages/application/src/handlers.ts, packages/application/src/hooks/useComponentTree.ts, packages/application/src/types.ts, packages/common/src/types/messaging.ts, packages/container/src/container.ts, packages/container/src/events.ts, packages/container/src/messaging.ts, packages/container/src/render.ts, packages/container/src/types.ts
This PR refactors container and application code to more explicitly reference the container as opposed to individual Components.
=> feat: ignore messages from different source

packages/compiler/src/import.ts
This PR updates the `esm.sh` package URL to use the `exports` query string, enabling tree shaking for imported modules. URLs will now specify all destructured imports across the container for a given package.
Fixes #405
=> feat: use `esm.sh` tree shaking params

packages/container/src/callbacks.ts, packages/container/src/messaging.ts, packages/container/src/serialize.ts, packages/container/src/types.ts
This PR refactors the `serializeArgs` method to remove the `callbacks` map argument. Container-level callbacks are already passed into the parent closure scope, so including them as direct parameters is unnecessarily confusing.
=> refactor: remove superfluous callbacks argument

packages/compiler/src/import.ts
Reverts near/bos-web-engine#407
I've noticed this breaking compatibility with several packages now (e.g. `zustand`). It looks like poor support on the esm.sh side (see https://esm.sh/v135/zustand@4.5.2?alias=react:preact/compat&external=preact&exports=create -> [indirect dep](https://esm.sh/v135/zustand@4.5.2/X-YS9yZWFjdDpwcmVhY3QvY29tcGF0CmUvcHJlYWN0CnRzL2NyZWF0ZQ/es2022/vanilla.js) (trying to import non-existent`create`), but needs more investigation.
=> Revert "feat: use `esm.sh` tree shaking params"

apps/demos/src/NPM/Tracker.tsx, packages/application/src/components/SandboxedIframe.tsx
This PR updates the container render logic to request renders at the Component level. When the `commit` hook is triggered on render, the target vnode is the root for the DOM subtree that changed. However the outer application only recognizes changes at the Component/container level. This means if the rendered vnode is the descendant of a Component, that subtree render will replace the entire Component DOM in the outer window. E.g. given
```jsx
const A = () => (<span>A</span>);
const B = () => (<span>B</span>);
...
<>
<A />
<B />
</>
```
The initial render would print both `A` and `B`, but if `<A />` were to re-render then only `A` would be printed. Since the outer application treats all render requests as coming directly from a Component, the updated descendant element overwrites the …
=> fix: render at the Component/container level

packages/social-db/src/constants.ts, packages/social-db/src/social-db.ts
If there is a specified block height (block id) the regular rpc call might not always return the component data.
Using the archival rpc url resolves this issue. 
To test this fix, please make sure you have `Enable block height versioning` flag set to `true` in the Dev Tools.
```tsx
import BlockHeightWithFlagTest from 'near://pavel-pagoda.near/BlockHeightWithFlagTest@115989105';
import BlockHeightWithFlagTestLatest from 'near://pavel-pagoda.near/BlockHeightWithFlagTest';
export default function () {
return (
<div>
<h1>Sandbox with a block height:</h1>
<BlockHeightWithFlagTest />
<hr />
<h1>Sandbox latest:</h1>
<BlockHeightWithFlagTestLatest />
</div>
);
}
```
Fixes https://github.com/near/bos-web-engine/issues/404
=> Use archival rpc calls if the block id is specified

packages/application/src/components/SandboxedIframe.tsx
This one-liner is fixing the infinite loop, causing the browser page to freeze.
Before merging this PR, this component would hit a loop after hitting the button to increment a value:
```tsx
import { useState } from 'react';
function Child() {
const [countChild, setCountChild] = useState(0);
const handleClick = () => setCountChild((x) => x + 1);
return (
<div>
<button onClick={handleClick}>++</button>
child: {countChild}
</div>
);
}
export default function () {
return (
<div>
<h1>Callback</h1>
<Child />
</div>
);
}
```
This fix resolves the issue.
=> Fix infinite loop on the container subtree run

apps/web/package.json, package.json, packages/hot-reload-server/package.json, pnpm-lock.yaml, turbo.json
I was able to simplify our Turbo commands and fix the `pnpm dev` command by manually upping the `concurrency` limit. My machine would never boot up the Next JS servers due all of the `watch` commands never resolving (by design). I did a bunch of testing with other values like `100%`, but that still didn't work on my machine - so I finally just settled on passing a fixed number of `30` for max concurrent scripts.
https://turbo.build/repo/docs/reference/command-line-reference/run#--concurrency
I did a bunch of testing on my machine and it seems like these changes certainly help fix a few issues. The `wallet-selector-control` package still likes to spit out a TypeScript error during the build step, but the package still builds and resolves correctly.
It appears that Turbo has issues …
=> Updating Turbo commands to fix build edge cases

apps/sandbox/package.json, apps/sandbox/src/hooks/useQueryParams.ts, apps/sandbox/src/pages/index.tsx, apps/web/src/components/WebEngineVariants.tsx, apps/web/src/hooks/useQueryParams.ts, packages/application/src/components/ComponentTree.tsx, packages/application/src/hooks/useComponents.ts, packages/application/src/hooks/useWebEngine.ts, packages/application/src/hooks/useWebEngineSandbox.ts, packages/application/src/types.ts, packages/common/src/types/index.ts, packages/common/src/types/url.ts, packages/compiler/src/compiler.ts, packages/compiler/src/types.ts, packages/sandbox/src/components/Preview.tsx, packages/sandbox/src/components/Sandbox.tsx, packages/sandbox/src/hooks/useSandboxStore.ts, pnpm-lock.yaml
Closes: https://github.com/near/react-on-chain/issues/334
Please check out this comment for more context on the implementation in this PR: https://github.com/near/react-on-chain/issues/334#issuecomment-2070858868
The implementation itself is pretty simple and should be easy to refactor if any of us have concerns down the road. Here's an example component you can check out: https://bos-web-engine-git-feat-read-url-f462bd-near-developer-console.vercel.app/near/RocTest?foobar=abc
I made sure this implementation will support Next's `<Link>` component (client side routing) if/when we start using that inside our RoC components. The query parameters update and the root component receives the updated props.
Viewing the gateway:
Viewing the sandbox:
=> Read URL Query Params MVP
