near/react-on-chain

- apps/web/pages/index.tsx
- apps/web/pages/transpiler.tsx
- packages/container/src/index.ts
- packages/container/src/injection.ts
- packages/container/src/serialize.ts
- packages/iframe/src/SandboxedIframe.tsx
This PR adds support for the `State` and `state` APIs for trusted Components.
> feat: state support for trusted (inlined) Components

- apps/web/hooks/index.ts
- apps/web/hooks/useWebEngine.ts
- apps/web/pages/index.tsx
- packages/application/src/handlers.ts
- packages/application/src/types.ts
- packages/container/src/builtins.ts
- packages/container/src/serialize.ts
- packages/container/src/types.ts
- packages/eslint-config-custom/index.js
- packages/iframe/src/SandboxedIframe.tsx
This PR refactors the component state management and event handling into a hook. The hook is initialized with the path to the root component, bringing the outer application closer to a conventional SPA implementation.
> feat: Outer application improvements

- apps/web/pages/[...root].tsx
- apps/web/pages/components/[...root].tsx
- apps/web/pages/index.tsx
This PR adds support for basic routing in the outer application.
> feat: URL routing

- apps/web/components/ComponentTree.tsx
- apps/web/components/index.ts
- apps/web/hooks/useComponentMetrics.ts
- apps/web/hooks/useWebEngine.ts
- apps/web/pages/[...root].tsx
- apps/web/pages/index.tsx
- apps/web/styles.css
- apps/web/workers/compiler.ts
- packages/application/src/component-container.ts
- packages/application/src/handlers.ts
- packages/application/src/index.ts
- packages/application/src/monitor.tsx
- packages/application/src/react.ts
- packages/application/src/types.ts
- packages/compiler/src/compiler.ts
- packages/compiler/src/parser.ts
- packages/container/src/api.ts
- packages/container/src/builtins.ts
- packages/container/src/events.ts
- packages/container/src/index.ts
- packages/container/src/messaging.ts
- packages/container/src/serialize.ts
- packages/container/src/types.ts
- packages/iframe/src/SandboxedIframe.tsx
This PR adds error handling for invalid Component paths, fixes a bug in calling the compiler worker, and renames the remaining `widget` references.
> feat: loading enhancements and renames

- apps/web/hooks/useComponentMetrics.ts
- apps/web/hooks/useWebEngine.ts
- apps/web/styles.css
- packages/application/src/component-container.ts
- packages/application/src/handlers.ts
- packages/application/src/index.ts
- packages/application/src/monitor.tsx
- packages/application/src/react.ts
- packages/application/src/types.ts
- packages/compiler/src/compiler.ts
- packages/container/src/events.ts
- packages/container/src/messaging.ts
- packages/container/src/serialize.ts
- packages/container/src/types.ts
- packages/iframe/src/SandboxedIframe.tsx
This PR overhauls the message passing and metrics functionality for a more streamlined implementation. The goal here was to address the pain points experienced in getting trusted loading working and tested, in particular the ability to see messages in a structured, readable format. I was able to clean up many of the interfaces, removing duplicate and unused types wherever possible.
> feat: messge and metrics enhancements

- apps/web/hooks/useWebEngine.ts
- apps/web/pages/[...root].tsx
- apps/web/styles.css
- packages/application/src/handlers.ts
- packages/application/src/monitor.tsx
- packages/application/src/types.ts
- packages/container/src/callbacks.ts
- packages/container/src/events.ts
- packages/container/src/index.ts
- packages/container/src/types.ts
- packages/iframe/src/SandboxedIframe.tsx
This PR makes the metrics layout a little easier to parse.
I decided to fixes #46 after finding the issue thanks to the updates on DOM callback invocations 🎉
> feat: metrics polish

- apps/web/hooks/useWebEngine.ts
- packages/compiler/src/component.ts
- packages/compiler/src/parser.ts
> fix: allow Component names with hyphens

- apps/web/package.json
- package.json
- packages/compiler/package.json
- packages/compiler/src/compiler.ts
- packages/compiler/src/transpile.ts
- pnpm-lock.yaml
> build: dependabot

- apps/web/pages/[[...root]].tsx
moves everything on page behind a check that we have processed the router params and are ready to start loading
> prevent error flash on load

- packages/compiler/src/transpile.ts
> TypeScript support

- architecture.md
Follow-up to #126 
Figma is not working for me at the moment but I'd like to consolidate the existing diagrams and add some for callbacks.
> docs: architecture updates

- press-release-faq.md
recommended by Eric
https://medium.com/agileinsider/press-releases-for-product-managers-everything-you-need-to-know-942485961e31
> WIP Press Release - FAQ

- .github/workflows/deploy-components-main.yml
- apps/demos/.bos-loader.toml
- apps/demos/.gitignore
- apps/demos/README.md
- apps/demos/globals.d.ts
- apps/demos/ignore/README.md
- apps/demos/package.json
- apps/demos/pnpm-lock.yaml
- apps/demos/src/HelloWorld.tsx
- apps/demos/src/LandingPage.tsx
- apps/demos/src/Posts/Account.tsx
- apps/demos/src/Posts/Feed.tsx
- apps/demos/src/Posts/Markdown.tsx
- apps/demos/src/Posts/Marked.tsx
- apps/demos/src/Posts/Post.tsx
- apps/demos/src/Posts/Sidebar.tsx
- apps/demos/src/StateAndTrust/Root.tsx
- apps/demos/src/StateAndTrust/SetParent.tsx
- apps/demos/src/StateAndTrust/Shape/Circle.tsx
- apps/demos/src/StateAndTrust/Shape/Square.tsx
- apps/demos/src/StateAndTrust/Shape/Triangle.tsx
- apps/demos/src/StateAndTrust/ShapeSet.tsx
- apps/demos/src/StateAndTrust/TrustTree.tsx
- apps/demos/tsconfig.json
- pnpm-lock.yaml
This PR brings in the existing demo Components, porting them to use the new `export` syntax. Fixes #164
> feat: demos with export

- packages/sandbox/package.json
- packages/sandbox/src/components/MonacoEditor.tsx
- packages/sandbox/src/monaco/auto-close-html-tags.ts
- pnpm-lock.yaml
Closes: https://github.com/near/bos-web-engine/issues/199
> Auto close HTML tags + Emmet

- packages/sandbox/src/components/Dropdown.tsx
- packages/sandbox/src/components/FileExplorer.tsx
- packages/sandbox/src/components/Layout.tsx
- packages/sandbox/src/components/MonacoEditor.tsx
- packages/sandbox/src/components/Preview.tsx
- packages/sandbox/src/components/Sandbox.tsx
- packages/sandbox/src/components/Tooltip.tsx
- packages/sandbox/src/hooks/useSandboxStore.ts
Closes: https://github.com/near/bos-web-engine/issues/202
> Pin Sandbox Preview

- packages/application/src/hooks/useComponents.ts
- packages/application/src/hooks/useWebEngineSandbox.ts
This PR enhances the CSS functionality to store rules on a custom element's stylesheet, allowing rules to be consistently reset.
Fixes #229
> feat: CSS reset

- apps/sandbox/src/styles/app.module.css
- apps/web/src/pages/_app.tsx
- apps/web/src/styles/app.module.css
- packages/sandbox/src/components/FileExplorer.module.css
- packages/sandbox/src/components/FileExplorer.tsx
- packages/sandbox/src/components/MonacoDiff.tsx
- packages/sandbox/src/components/MonacoEditor.tsx
- packages/sandbox/src/components/Preview.module.css
- packages/sandbox/src/components/Preview.tsx
- packages/sandbox/src/components/Sandbox.tsx
- packages/sandbox/src/components/SidebarActions.module.css
- packages/sandbox/src/components/SidebarActions.tsx
- packages/sandbox/src/constants.ts
- packages/ui/reset.css
- packages/ui/src/components/Button.module.css
- packages/ui/src/components/Checkbox.module.css
- packages/ui/src/components/Dropdown.module.css
- packages/ui/src/components/Dropdown.tsx
- packages/ui/src/components/Theme.module.css
- packages/ui/src/components/Theme.tsx
- packages/ui/src/components/Tooltip.module.css
- packages/ui/src/components/Tooltip.tsx
- packages/wallet-selector-control/src/components/WalletSelectorControl.module.css
- packages/wallet-selector-control/src/components/WalletSelectorControl.tsx
Closes: https://github.com/near/bos-web-engine/issues/256
Pulled in the official color scheme from `near.org` to make our sandbox and demo gateway look a bit more familiar. This means we'll be locked in to a light color scheme for the time being. We can consider adding support for dark and light mode down the road.
> Theme Update

- packages/compiler/src/component.ts
- packages/compiler/src/css.ts
- packages/sandbox/src/components/Preview.tsx
This PR addresses some CSS inconsistencies. Fixes #270
> fix: CSS inconsistencies

- packages/sandbox/src/components/Preview.tsx
This PR removes syntax debugging code merged in #271
> chore: remove className interpolation

- packages/compiler/src/css.ts
This PR adds support for specifying pseudo-classes on top-level class names. Fixes #276
> fix: support pseudo-selectors on top-level class names

- apps/demos/src/LandingPage.tsx
- apps/demos/src/NPM/Lodash.tsx
- apps/demos/src/NPM/PhosphorIcons.tsx
- apps/demos/src/NPM/React/Hooks/UseMemo.tsx
- apps/demos/src/NPM/React/Hooks/UseRef.tsx
- apps/demos/src/NPM/ReactSyntaxHighlighter.tsx
- apps/demos/src/NPM/Tracker.tsx
- apps/demos/src/NPM/Tracker/ComponentEntry.tsx
- apps/demos/src/NPM/Zustand.tsx
- apps/web/src/components/Inspector.tsx
This PR adds demo Components for external NPM packages. Currently just a jumble of working and non-working, overview page TBD.
Feel free to push more to this branch 🙂
> feat: demo Components for external packages

- apps/web/package.json
- apps/web/src/pages/_app.tsx
- pnpm-lock.yaml
Closes: https://github.com/near/bos-web-engine/issues/258
Some of our demo pages might look a bit ugly for the short term, but I'll be following up with updated styles.
> Remove Bootstrap

- packages/compiler/src/source.ts
> handle components without css

- packages/sandbox/src/components/FileOpener.tsx
- packages/sandbox/src/utils.ts
Closes: https://github.com/near/bos-web-engine/issues/305
> Reconcile "." and "/" when opening or renaming a file

- packages/container/src/container.ts
Fixes `Cannot read properties of undefined (reading 'isRootContainerComponent')`
> fix: undefined Component

- apps/docs/docs/alpha/building-decentralized-frontends/imports.md
This PR adds some extra context to the `imports` documentation
> docs: additional context on imports

- packages/sandbox/.gitignore
- packages/sandbox/dts-bundle-generator.config.js
- packages/sandbox/package.json
- packages/sandbox/rollup.config.js
- packages/sandbox/src/components/MonacoEditor.tsx
- packages/sandbox/src/constants.ts
- packages/sandbox/src/global.d.ts
- packages/sandbox/src/plugins.ts
- packages/social-db-plugin/src/index.ts
- packages/social-db/src/social-db.ts
- packages/wallet-selector-plugin/src/index.ts
- pnpm-lock.yaml
Closes: https://github.com/near/bos-web-engine/issues/312
After smashing my head against the wall for awhile, I found a decent direction for resolving the plugin imports and types in the Sandbox IDE. I left detailed notes in `packages/sandbox/src/plugins.ts`.
I went ahead and also updated our `SocialGet` demo with proper types.
> Resolve plugin imports and types in the sandbox IDE

- apps/demos/src/AlphaDashboardPage.tsx
- apps/demos/src/HelloWorld.tsx
- apps/demos/src/NPM/Tracker.tsx
- apps/demos/src/Post.tsx
- apps/demos/src/SocialFeedPage.tsx
- apps/demos/src/StateAndTrust/Root.tsx
- apps/demos/src/StateAndTrust/SetParent.tsx
- apps/demos/src/StateAndTrust/ShapeSet.tsx
- apps/demos/src/StateAndTrust/TrustTree.tsx
This PR updates the demo Components to use the new `props` interface.
> chore: update demos to use new props interface

- packages/compiler/package.json
- packages/compiler/src/css.ts
- pnpm-lock.yaml
Not sure how you want to decide what browser compatibility query to insert, so I put in what browserslist uses as the default.
> resolves #364 browsertarget compatibility.
